languageCode = "en"
languageName = "English"
weight = 1
title = "TechGeeks"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  # secondaryLogo = "PATH"
  description = "Student Innovation Club's Website @ Maratha Mandal Engineering College, Belagavi. A Website to Showcase club's Achievements, Members and Projects."
  copyright = "© Copyright { year }, All Rights Reserved | TechGeeks"

[author]
  name = "Student Innovation Club"
  image = "img/blowfish_logo.png"
  headline = "At Maratha Mandal Engineering College, Belagavi"
  bio = "Student Innovation Club's Website @ Maratha Mandal Engineering College, Belagavi. A Website to Showcase club's Achievements, Members and Projects."
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { mastodon = "https://masto.ai/@blowfish" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]

  