languageCode = "en"
languageName = "English"
weight = 1
title = "INNOVATION | TechGeeks"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "logo/png/Black_logo-no_background_cropped.png"
  secondaryLogo = "logo/png/White_logo-no_background_cropped.png"
  description = "Student Innovation Club's Website @ Maratha Mandal's Engineering College, Belagavi. A Website to Showcase club's Achievements, Members and Projects."
  copyright = "© Copyright { year }, All Rights Reserved | TechGeeks"

[params.author]
  name = "Student Innovation Club"
  image = "logo/mmec_logo.png"
  headline = "At Maratha Mandal's Engineering College, Belagavi"
  bio = "Student Innovation Club's Website @ Maratha Mandal's Engineering College, Belagavi. A Website to Showcase club's Achievements, Members and Projects."
  links = [
    { email = "mailto:sicmmec@gmail.com" },
    { facebook = "https://www.facebook.com/profile.php?id=61556612242990"},
    { github = "https://github.com/SICMMEC" },
    { instagram = "https://www.instagram.com/techgeeks.sicmmec/" },
    { linkedin = "https://www.linkedin.com/in/sicmmec/" },
    { x-twitter = "https://twitter.com/sicmmec" },
    { youtube = "https://www.youtube.com/@SICMMEC" }
  ]

  